name: Publish Tag

on:
  workflow_dispatch:

# This GitHub Action bumps the version based on commit messages.
# If a commit message contains either #major, #minor or #patch
# the action will increment the associated version number.
# If no commit message contains one of these keywords,
#the action will increment the patch version.
jobs:
  publish-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version
        uses: gabeduke/bumpver-action@v1.0.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
