# publish.yml
name: Publish

on:
  push:
    tags: "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno 2
        uses: denoland/setup-deno@v2

      - name: Set version # Get the version from the tag and update to 'deno.json[c]'
        uses: MAKS11060/deno-publish-version@v2
        with:
          config-file: deno.jsonc # or deno.json
          tag: ${{ github.ref_name }}

      - name: Publish to JSR
        run: deno publish --allow-dirty
