name: Publish Tag

on:
  workflow_dispatch:

# This GitHub Action bumps the version based on commit messages.
# If a commit message contains either #major, #minor or #patch
# the action will increment the associated version number.
# If no commit message contains one of these keywords,
#the action will increment the patch version.
jobs:
  publish-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version
        uses: gabeduke/bumpver-action@v1.0.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Deno 2
        uses: denoland/setup-deno@v2

      - name: "Get Tag"
        id: gettag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v0.1.0 # Optional fallback tag to use when no tag can be found

      - name: Set version # Get the version from the tag and update to 'deno.json[c]'
        uses: MAKS11060/deno-publish-version@v2
        with:
          config-file: deno.json # or deno.json
          tag: ${{ steps.gettag.outputs.tag }}

      - name: Publish to JSR
        run: deno publish --allow-dirty
